[package]
name = "decimal_rs"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "decimal_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
rust_decimal = { version = "1.29.1", features = ["maths"] }
